version: "3.9"

services:
  api:
    build: .
    container_name: pdf-chat-api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./evaluation:/app/evaluation
    env_file:
      - .env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  streamlit:
    build: .
    container_name: pdf-chat-ui
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    command: ["streamlit", "run", "app/streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
      - streamlit